version: '{build}'

image: Visual Studio 2017
platform:
  - x64

skip_tags: true
skip_branch_with_pr: true
clone_depth: 1
max_jobs: 3

cache:
  - '%LOCALAPPDATA%\Composer'
  - '%LOCALAPPDATA%\Temp\Chocolatey'

environment:
  ANSICON: 121x90 (121x90)
  matrix:
    - { AST_VERSION: '1.0.14', PHP_VERSION: '7.4.3', VC_VERSION: '15', XDEBUG_VERSION: '3.0.4' }

install:
  # Enable Windows Update service, needed to install vcredist2015 (dependency of php)
  - ps: Set-Service wuauserv -StartupType Manual
  - choco config set cacheLocation %LOCALAPPDATA%\Temp\Chocolatey
  - choco install -y php --version %PHP_VERSION%
  - choco install -y composer
  - refreshenv
  # Install XDebug for code coverage and AST for phan/phan
  - ps: |
      $phpMinorVersion = $env:PHP_VERSION -replace '\.\d+$'
      $phpDir = (Get-Item (Get-Command php).Source).Directory.FullName
      $phpExtDir = "$phpDir\ext"
      $xdebugUrl = "https://windows.php.net/downloads/pecl/releases/xdebug/$env:XDEBUG_VERSION/php_xdebug-$env:XDEBUG_VERSION-$phpMinorVersion-nts-vc$env:VC_VERSION-x64.zip"
      echo "Downloading $xdebugUrl"
      $xdebugZipPath = "C:\msys64\tmp\php_xdebug.zip"
      Invoke-WebRequest $xdebugUrl -OutFile $xdebugZipPath
      7z x $xdebugZipPath "-o$phpExtDir" php_xdebug.dll
      $astUrl = "https://windows.php.net/downloads/pecl/releases/ast/$env:AST_VERSION/php_ast-$env:AST_VERSION-$phpMinorVersion-nts-vc$env:VC_VERSION-x64.zip"
      $astZipPath = "C:\msys64\tmp\php_ast.zip"
      echo "Downloading $astUrl"
      Invoke-WebRequest $astUrl -OutFile $astZipPath
      7z x $astZipPath "-o$phpExtDir" php_ast.dll
      Add-Content $phpDir\php.ini @"
      zend_extension=xdebug
      extension_dir=$phpExtDir
      extension=php_ast.dll
      "@
      php -m
  - composer install --no-interaction --no-progress --prefer-dist

build: off

test_script:
  - vendor\bin\phpcs -n
  - vendor\bin\phan --load-baseline=.\.phan\baseline.php
  - vendor\bin\phpunit --coverage-clover=coverage.xml --colors=always

after_test:
  - ps: |
      # Delete vendor because it causes problems with codecovs report search
      # https://github.com/codecov/codecov-bash/issues/96
      Remove-Item -Recurse -Force vendor
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile codecov.sh
      bash codecov.sh -f 'coverage/coverage.xml'
